### ISSUE TITLE
Windows panic: file-explorer

### ISSUE THREAD

**Issue by NCrashed** [DioxusLabs/example-projects#3]
Version: rustc 1.59.0-nightly (e012a191d 2022-01-06)
System: Windows 10
Target: x86_64-pc-windows-msvc

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: WebView2Error(webview2 error, HRESULT 0x80070002)', C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\dioxus-desktop-0.1.4\src\lib.rs:355:14
stack backtrace:
   0:     0x7ff789c6e01f - std::backtrace_rs::backtrace::dbghelp::trace
                               at /rustc/e012a191d768adeda1ee36a99ef8b92d51920154\/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98
   1:     0x7ff789c6e01f - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/e012a191d768adeda1ee36a99ef8b92d51920154\/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff789c6e01f - std::sys_common::backtrace::_print_fmt
                               at /rustc/e012a191d768adeda1ee36a99ef8b92d51920154\/library\std\src\sys_common\backtrace.rs:67
   3:     0x7ff789c6e01f - std::sys_common::backtrace::_print::impl$0::fmt
                               at /rustc/e012a191d768adeda1ee36a99ef8b92d51920154\/library\std\src\sys_common\backtrace.rs:46
   4:     0x7ff789c8547a - core::fmt::write
                               at /rustc/e012a191d768adeda1ee36a99ef8b92d51920154\/library\core\src\fmt\mod.rs:1168
   5:     0x7ff789c69dc8 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/e012a191d768adeda1ee36a99ef8b92d51920154\/library\std\src\io\mod.rs:1660
   6:     0x7ff789c70bbb - std::sys_common::backtrace::_print
                               at /rustc/e012a191d768adeda1ee36a99ef8b92d51920154\/library\std\src\sys_common\backtrace.rs:49
   7:     0x7ff789c70bbb - std::sys_common::backtrace::print
                               at /rustc/e012a191d768adeda1ee36a99ef8b92d51920154\/library\std\src\sys_common\backtrace.rs:36
   8:     0x7ff789c70bbb - std::panicking::default_hook::closure$1
                               at /rustc/e012a191d768adeda1ee36a99ef8b92d51920154\/library\std\src\panicking.rs:211
   9:     0x7ff789c706b4 - std::panicking::default_hook
                               at /rustc/e012a191d768adeda1ee36a99ef8b92d51920154\/library\std\src\panicking.rs:228
  10:     0x7ff789c710bc - std::panicking::rust_panic_with_hook
                               at /rustc/e012a191d768adeda1ee36a99ef8b92d51920154\/library\std\src\panicking.rs:606
  11:     0x7ff789c70f7b - std::panicking::begin_panic_handler::closure$0
                               at /rustc/e012a191d768adeda1ee36a99ef8b92d51920154\/library\std\src\panicking.rs:502
  12:     0x7ff789c6e967 - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure$0,never$>
                               at /rustc/e012a191d768adeda1ee36a99ef8b92d51920154\/library\std\src\sys_common\backtrace.rs:139
  13:     0x7ff789c70c79 - std::panicking::begin_panic_handler
                               at /rustc/e012a191d768adeda1ee36a99ef8b92d51920154\/library\std\src\panicking.rs:498
  14:     0x7ff789c8ebe0 - core::panicking::panic_fmt
                               at /rustc/e012a191d768adeda1ee36a99ef8b92d51920154\/library\core\src\panicking.rs:107
  15:     0x7ff789c8ecf3 - core::result::unwrap_failed
                               at /rustc/e012a191d768adeda1ee36a99ef8b92d51920154\/library\core\src\result.rs:1690
  16:     0x7ff7899a69f5 - enum$<core::result::Result<wry::webview::WebView,enum$<wry::Error> > >::unwrap<wry::webview::WebView,enum$<wry::Error> >
                               at /rustc/e012a191d768adeda1ee36a99ef8b92d51920154\library\core\src\result.rs:1018
  17:     0x7ff789969a5b - dioxus_desktop::DesktopController::new_window
                               at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\dioxus-desktop-0.1.4\src\lib.rs:318
  18:     0x7ff789935867 - dioxus_desktop::launch_with_props::closure$0<tuple$<>,file_explorer::main::closure$0>
                               at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\dioxus-desktop-0.1.4\src\lib.rs:167
  19:     0x7ff789952371 - tao::platform_impl::platform::event_loop::impl$2::run_return::closure$0<enum$<dioxus_desktop::UserWindowEvent>,dioxus_desktop::launch_with_props::closure$0>
                               at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\tao-0.5.2\src\platform_impl\windows\event_loop.rs:219
  20:     0x7ff7899626d4 - alloc::boxed::impl$45::call_mut<tuple$<enum$<tao::event::Event<enum$<dioxus_desktop::UserWindowEvent> > >,ref_mut$<enum$<tao::event_loop::ControlFlow> > >,dyn$<core::ops::function::FnMut<tuple$<enum$<tao::event::Event<enum$<dioxus_desktop::UserWindowEvent
                               at /rustc/e012a191d768adeda1ee36a99ef8b92d51920154\library\alloc\src\boxed.rs:1861
  21:     0x7ff7899801d7 - tao::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure$0<enum$<dioxus_desktop::UserWindowEvent> >
                               at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\tao-0.5.2\src\platform_impl\windows\event_loop\runner.rs:249
  22:     0x7ff78998f184 - core::panic::unwind_safe::impl$23::call_once<tuple$<>,tao::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure$0>
                               at /rustc/e012a191d768adeda1ee36a99ef8b92d51920154\library\core\src\panic\unwind_safe.rs:271
  23:     0x7ff7899a83b1 - std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<tao::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure$0>,tuple$<> >
                               at /rustc/e012a191d768adeda1ee36a99ef8b92d51920154\library\std\src\panicking.rs:406
  24:     0x7ff7899a8983 - std::panicking::panicking
  25:     0x7ff7899a7f4b - std::panicking::try<tuple$<>,core::panic::unwind_safe::AssertUnwindSafe<tao::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure$0> >
                               at /rustc/e012a191d768adeda1ee36a99ef8b92d51920154\library\std\src\panicking.rs:370
  26:     0x7ff789973444 - std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<tao::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure$0>,tuple$<> >
                               at /rustc/e012a191d768adeda1ee36a99ef8b92d51920154\library\std\src\panic.rs:133
  27:     0x7ff78997f43b - tao::platform_impl::platform::event_loop::runner::EventLoopRunner<enum$<dioxus_desktop::UserWindowEvent> >::catch_unwind<enum$<dioxus_desktop::UserWindowEvent>,tuple$<>,tao::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure$
                               at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\tao-0.5.2\src\platform_impl\windows\event_loop\runner.rs:155
  28:     0x7ff78997ff03 - tao::platform_impl::platform::event_loop::runner::EventLoopRunner<enum$<dioxus_desktop::UserWindowEvent> >::call_event_handler<enum$<dioxus_desktop::UserWindowEvent> >
                               at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\tao-0.5.2\src\platform_impl\windows\event_loop\runner.rs:243
  29:     0x7ff789980d32 - tao::platform_impl::platform::event_loop::runner::EventLoopRunner<enum$<dioxus_desktop::UserWindowEvent> >::call_new_events<enum$<dioxus_desktop::UserWindowEvent> >
                               at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\tao-0.5.2\src\platform_impl\windows\event_loop\runner.rs:395
  30:     0x7ff789980721 - tao::platform_impl::platform::event_loop::runner::EventLoopRunner<enum$<dioxus_desktop::UserWindowEvent> >::move_state_to<enum$<dioxus_desktop::UserWindowEvent> >
                               at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\tao-0.5.2\src\platform_impl\windows\event_loop\runner.rs:311
  31:     0x7ff78997fa87 - tao::platform_impl::platform::event_loop::runner::EventLoopRunner<enum$<dioxus_desktop::UserWindowEvent> >::poll<enum$<dioxus_desktop::UserWindowEvent> >
                               at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\tao-0.5.2\src\platform_impl\windows\event_loop\runner.rs:204
  32:     0x7ff789951ef1 - tao::platform_impl::platform::event_loop::EventLoop<enum$<dioxus_desktop::UserWindowEvent> >::run_return<enum$<dioxus_desktop::UserWindowEvent>,dioxus_desktop::launch_with_props::closure$0>
                               at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\tao-0.5.2\src\platform_impl\windows\event_loop.rs:228
  33:     0x7ff789951d5f - tao::platform_impl::platform::event_loop::EventLoop<enum$<dioxus_desktop::UserWindowEvent> >::run<enum$<dioxus_desktop::UserWindowEvent>,dioxus_desktop::launch_with_props::closure$0>
                               at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\tao-0.5.2\src\platform_impl\windows\event_loop.rs:203
  34:     0x7ff7899514b5 - tao::event_loop::EventLoop<enum$<dioxus_desktop::UserWindowEvent> >::run<enum$<dioxus_desktop::UserWindowEvent>,dioxus_desktop::launch_with_props::closure$0>
                               at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\tao-0.5.2\src\event_loop.rs:151
  35:     0x7ff78993541e - dioxus_desktop::launch_with_props<tuple$<>,file_explorer::main::closure$0>
                               at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\dioxus-desktop-0.1.4\src\lib.rs:163
  36:     0x7ff7899351ee - dioxus_desktop::launch_cfg<file_explorer::main::closure$0>
                               at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\dioxus-desktop-0.1.4\src\lib.rs:124
  37:     0x7ff789935d00 - file_explorer::main
                               at C:\dev\example-projects\file-explorer\src\main.rs:12
  38:     0x7ff78994e41b - core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
                               at /rustc/e012a191d768adeda1ee36a99ef8b92d51920154\library\core\src\ops\function.rs:227
  39:     0x7ff78995177b - std::sys_common::backtrace::__rust_begin_short_backtrace<void (*)(),tuple$<> >
                               at /rustc/e012a191d768adeda1ee36a99ef8b92d51920154\library\std\src\sys_common\backtrace.rs:123
  40:     0x7ff789939261 - std::rt::lang_start::closure$0<tuple$<> >
                               at /rustc/e012a191d768adeda1ee36a99ef8b92d51920154\library\std\src\rt.rs:145
  41:     0x7ff789c6d87f - core::ops::function::impls::impl$2::call_once
                               at /rustc/e012a191d768adeda1ee36a99ef8b92d51920154\library\core\src\ops\function.rs:259
  42:     0x7ff789c6d87f - std::panicking::try::do_call
                               at /rustc/e012a191d768adeda1ee36a99ef8b92d51920154\/library\std\src\panicking.rs:406
  43:     0x7ff789c6d87f - std::panicking::try
                               at /rustc/e012a191d768adeda1ee36a99ef8b92d51920154\/library\std\src\panicking.rs:370
  44:     0x7ff789c6d87f - std::panic::catch_unwind
                               at /rustc/e012a191d768adeda1ee36a99ef8b92d51920154\/library\std\src\panic.rs:133
  45:     0x7ff789c6d87f - std::rt::lang_start_internal::closure$2
                               at /rustc/e012a191d768adeda1ee36a99ef8b92d51920154\/library\std\src\rt.rs:128
  46:     0x7ff789c6d87f - std::panicking::try::do_call
                               at /rustc/e012a191d768adeda1ee36a99ef8b92d51920154\/library\std\src\panicking.rs:406
  47:     0x7ff789c6d87f - std::panicking::try
                               at /rustc/e012a191d768adeda1ee36a99ef8b92d51920154\/library\std\src\panicking.rs:370
  48:     0x7ff789c6d87f - std::panic::catch_unwind
                               at /rustc/e012a191d768adeda1ee36a99ef8b92d51920154\/library\std\src\panic.rs:133
  49:     0x7ff789c6d87f - std::rt::lang_start_internal
                               at /rustc/e012a191d768adeda1ee36a99ef8b92d51920154\/library\std\src\rt.rs:128
  50:     0x7ff78993922f - std::rt::lang_start<tuple$<> >
                               at /rustc/e012a191d768adeda1ee36a99ef8b92d51920154\library\std\src\rt.rs:144
  51:     0x7ff7899369e6 - main
  52:     0x7ff789c8cc94 - invoke_main
                               at d:\agent\_work\63\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  53:     0x7ff789c8cc94 - __scrt_common_main_seh
                               at d:\agent\_work\63\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  54:     0x7ffe155f7034 - BaseThreadInitThunk
  55:     0x7ffe161fcec1 - RtlUserThreadStart
error: process didn't exit successfully: `target\debug\file-explorer.exe` (exit code: 101)
```

**Comment by grayfallstown** [comment]
Make sure webview2 is installed
[How-to-check-for-and-install-WebView2](https://support.templafy.com/hc/en-us/articles/360017470437-How-to-check-for-and-install-WebView2)
